# Generated by Django 5.2 on 2025-07-13 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titulo', '0002_titulo_generos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='titulo.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do vídeo')),
                ('hls_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link HLS (m3u8)')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='temporadas.temporada')),
            ],
        ),
    ]
