# Generated by Django 5.2.3 on 2025-06-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrador",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="administrador",
            name="is_superadmin",
            field=models.BooleanField(default=False),
        ),
    ]
