# Generated by Django 5.1.7 on 2025-07-13 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Titulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("ano_lancamento", models.PositiveIntegerField()),
                ("sinopse", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "titulo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="titulo.titulo",
                    ),
                ),
                ("duracao_minutos", models.PositiveIntegerField()),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Link do vídeo",
                    ),
                ),
                (
                    "capa",
                    models.ImageField(blank=True, null=True, upload_to="capas_filmes/"),
                ),
                (
                    "hls_link",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Link HLS (m3u8)",
                    ),
                ),
            ],
            bases=("titulo.titulo",),
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "titulo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="titulo.titulo",
                    ),
                ),
                ("numero_temporadas", models.PositiveIntegerField()),
            ],
            bases=("titulo.titulo",),
        ),
    ]
