# Generated by Django 5.1.7 on 2025-07-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titulo", "0002_titulo_generos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serie",
            name="numero_temporadas",
        ),
        migrations.AddField(
            model_name="serie",
            name="hls_link_trailler",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Link HLS (m3u8)"
            ),
        ),
    ]
