# Generated by Django 5.1.7 on 2025-07-15 14:02

import titulo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("titulo", "0004_remove_filme_capa_titulo_capa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titulo",
            name="capa",
            field=models.ImageField(
                blank=True, null=True, upload_to=titulo.models.gerar_nome_arquivo
            ),
        ),
    ]
